apiVersion: v1
version: 4.0.3
appVersion: 4.0.3
name: podinfo
engine: gotpl
description: Podinfo Helm chart for Kubernetes
home: https://github.com/guan840912/podinfo
maintainers:
- email: stefanprodan@users.noreply.github.com
  name: stefanprodan
sources:
- https://github.com/guan840912/podinfo
